services:
  landing:
    build:
      context: .
    user: "${MY_UID}:${MY_GID}"
    ports:
      - "8000:8000"
    volumes:
      - ./portal-access:/docs
    command: tail -f /dev/null
  api-documentation:
    build:
      context: .
    user: "${MY_UID}:${MY_GID}"
    ports:
      - "8001:8001"
    volumes:
      - ./api-documentation:/docs
    command: tail -f /dev/null

  data-model-user-guide:
    build:
      context: .
    user: "${MY_UID}:${MY_GID}"
    ports:
      - "8002:8002"
    volumes:
      - ${GITHUB_WORKSPACE:-.}:/workspace
    working_dir: /workspace/data-model-user-guide
    command: tail -f /dev/null

  user-portal-documentation:
    build:
      context: .
    user: "${MY_UID}:${MY_GID}"
    ports:
      - "8003:8003"
    volumes:
      - ./user-portal-documentation:/docs
    command: tail -f /dev/null
